// <auto-generated />
using System;
using HalfChess.Client.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HalfChess.Client.Migrations
{
    [DbContext(typeof(GameReplayContext))]
    partial class GameReplayContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("HalfChess.Client.Data.Models.ClientGame", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("HalfChess.Client.Data.Models.ClientMove", b =>
                {
                    b.Property<int>("MoveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromPosition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCapture")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MoveTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PieceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToPosition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MoveId");

                    b.HasIndex("GameId");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("HalfChess.Client.Data.Models.ClientMove", b =>
                {
                    b.HasOne("HalfChess.Client.Data.Models.ClientGame", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("HalfChess.Client.Data.Models.ClientGame", b =>
                {
                    b.Navigation("Moves");
                });
#pragma warning restore 612, 618
        }
    }
}
